---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argocd-appset-substitute-plugin.fullname" . }}
  labels:
  {{- include "argocd-appset-substitute-plugin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
