{{- if and .Values.rbac.create (empty .Values.controller.namespaces) (empty .Values.controller.useExistingClusterRoleName) -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "argocd-appset-substitute-plugin.controller.labels" . | nindent 4 }}
  name: {{ include "argocd-appset-substitute-plugin.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "argocd-appset-substitute-plugin.serviceAccountName.controller" . }}
    namespace: {{ include "argocd-appset-substitute-plugin.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argocd-appset-substitute-plugin.clusterRoleName" . }}
{{- end }}