{{- if and .Values.rbac.create (empty .Values.controller.useExistingClusterRoleName) -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    {{- include "argocd-appset-substitute-plugin.controller.labels" . | nindent 4 }}
  name: {{ include "argocd-appset-substitute-plugin.clusterRoleName" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}