apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-appset-substitute-plugin.fullname" . }}
  labels:
  {{- include "argocd-appset-substitute-plugin.labels" . | nindent 4 }}
data:
  token: "${{ include "argocd-appset-substitute-plugin.fullname" . }}:token"
  baseUrl: "http://{{ include "argocd-appset-substitute-plugin.fullname" . }}.{{ .Release.Namespace }}.svc"
  requestTimeout: "60"