{{- if (empty .Values.controller.configMapOverrideName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
{{- with .Values.controller.configMapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "argocd-appset-substitute-plugin.controller.labels" . | nindent 4 }}
    {{- with .Values.controller.extraConfigmapLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "argocd-appset-substitute-plugin.controller.fullname" . }}
  namespace: {{ include "argocd-appset-substitute-plugin.namespace" . }}
data:
  token: "${{ include "argocd-appset-substitute-plugin.controller.fullname" . }}:token"
  baseUrl: "http://{{ include "argocd-appset-substitute-plugin.controller.fullname" . }}.{{ .Release.Namespace }}.svc"
  requestTimeout: "60"
{{- end -}}