{{ $password := (randAlphaNum 24 | nospace) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-appset-substitute-plugin.fullname" . }}
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argocd-appset-substitute-plugin.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
type: Opaque
data:
  plugin.plugin.token: {{ $password }}
  APP_TOKEN: {{ $password }}
  APP_PORT: {{ .Values.port | default "4444" }}