apiVersion: v1
kind: Secret
metadata:
{{- with .Values.controller.configMapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ include "argocd-appset-substitute-plugin.controller.fullname" . }}
  labels:
    {{- with .Values.controller.extraConfigmapLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  namespace: {{ include "argocd-appset-substitute-plugin.namespace" . }}
type: Opaque
data:
  {{- $token := include "argocd-appset-substitute-plugin.controller.secret.token" . | quote }}
  token: {{ $token }}
  APP_TOKEN: {{ $token }}
  APP_PORT: {{ .Values.controller.port | default "4444" | b64enc }}