---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-appset-substitute-plugin.fullname" . }}
  labels:
  {{- include "argocd-appset-substitute-plugin.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "argocd-appset-substitute-plugin.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}