{{- if .Values.serviceAccounts.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "argocd-appset-substitute-plugin.controller.labels" . | nindent 4 }}
    {{- if .Values.serviceAccounts.controller.labels }}
      {{- toYaml .Values.serviceAccounts.controller.labels | nindent 4 }}
    {{- end }}
  name: {{ template "argocd-appset-substitute-plugin.serviceAccountName.controller" . }}
  namespace: {{ include "argocd-appset-substitute-plugin.namespace" . }}
    {{- if .Values.serviceAccounts.controller.annotations }}
    annotations:
      {{- toYaml .Values.serviceAccounts.controller.annotations | nindent 4 }}
    {{- end }}
{{- if kindIs "bool" .Values.controller.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.controller.automountServiceAccountToken }}
{{- else if kindIs "bool" .Values.serviceAccounts.controller.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.serviceAccounts.controller.automountServiceAccountToken }}
{{- end }}
{{- end }}