name: E2E Tests

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/e2e-tests-call.yaml
    with:
      version: v0.0.0
    secrets: inherit
