name: Release dev

on:
  push:
    paths-ignore:
    - 'charts/**'
    branches:
    - 'dev'

permissions:
  contents: write
  packages: write

jobs:
  version:
    name: Version
    uses: ./.github/workflows/version.yaml

  tagging:
    if: startsWith(needs.version.outputs.version, 'v')
    name: Tagging
    uses: ./.github/workflows/tagging.yaml
    needs:
    - version
    with:
      source: ${{ github.event.after }}
      tag: ${{ needs.version.outputs.version }}
      create-release: ${{ startsWith(needs.version.outputs.version, 'v') }}
    secrets: inherit


