name: Release Dev

on:
  push:
    paths-ignore:
    - 'charts/**'
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  version:
    name: Version
    uses: ./.github/workflows/version.yaml